"""add flexible unit conversion system

Revision ID: 22d53bc57949
Revises: d99458327a4b
Create Date: 2026-03-15 14:29:18.112842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d53bc57949'
down_revision: Union[str, Sequence[str], None] = 'd99458327a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_unit_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'unit_name', name='uq_product_unit_name')
    )
    op.create_index(op.f('ix_product_unit_conversions_id'), 'product_unit_conversions', ['id'], unique=False)
    op.create_index(op.f('ix_product_unit_conversions_product_id'), 'product_unit_conversions', ['product_id'], unique=False)
    op.alter_column('inventory', 'quantity_available',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    # Step 1: add column as nullable
    op.add_column('products', sa.Column('base_unit', sa.String(), nullable=True))

    # Step 2: set default base unit for existing products
    op.execute("UPDATE products SET base_unit = 'Unit' WHERE base_unit IS NULL")

    # Step 3: enforce NOT NULL
    op.alter_column('products', 'base_unit', nullable=False)


    # Step 1: add column as nullable
    op.add_column('sale_items', sa.Column('unit_name', sa.String(), nullable=True))

    # Step 2: populate existing rows with default value
    op.execute("UPDATE sale_items SET unit_name = 'Unit' WHERE unit_name IS NULL")

    # Step 3: enforce NOT NULL
    op.alter_column('sale_items', 'unit_name', nullable=False)

    
    op.alter_column('sale_items', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'quantity',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('sale_items', 'unit_name')
    op.drop_column('products', 'base_unit')
    op.alter_column('inventory', 'quantity_available',
               existing_type=sa.Numeric(precision=14, scale=4),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_unit_conversions_product_id'), table_name='product_unit_conversions')
    op.drop_index(op.f('ix_product_unit_conversions_id'), table_name='product_unit_conversions')
    op.drop_table('product_unit_conversions')
    # ### end Alembic commands ###
