"""add streak fields to businesses table

Revision ID: 8276a00f3321
Revises: 22d53bc57949
Create Date: 2026-03-27 15:02:31.057936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8276a00f3321'
down_revision: Union[str, Sequence[str], None] = '22d53bc57949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # Add last_sale_date first (nullable is fine)
    op.add_column('businesses', sa.Column('last_sale_date', sa.Date(), nullable=True))
    
    # Add current_streak with a default value for existing rows
    op.add_column('businesses', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'current_streak')
    op.drop_column('businesses', 'last_sale_date')
    # ### end Alembic commands ###
