"""add_trial_columns_to_users

Revision ID: d9411dfe55ca
Revises: 8276a00f3321
Create Date: 2026-05-07 11:16:31.888489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9411dfe55ca'
down_revision: Union[str, Sequence[str], None] = '8276a00f3321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_end_date')
    op.drop_column('users', 'trial_start_date')
    # ### end Alembic commands ###
